CREATE TABLE merchands (
	code CHAR(10) PRIMARY KEY,
	name VARCHAR(64),
	country VARCHAR(16)
);
INSERT INTO merchands (code, name, country) VALUES ('88-1479529', 'Walsh, Olson and Mertz', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('91-3366138', 'Aufderhar-O''Hara', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('17-7438780', 'Grady-Berge', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('12-4266726', 'Graham LLC', 'Malaysia');
INSERT INTO merchands (code, name, country) VALUES ('50-9541874', 'Bartoletti-Wilderman', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('09-4595813', 'Macejkovic Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('50-0741111', 'Feil, Leannon and Lesch', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('42-9416123', 'Halvorson, Rowe and Huel', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('11-3246709', 'Lueilwitz-Kemmer', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('20-5111076', 'Ondricka-McLaughlin', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('88-1771553', 'Funk-Herzog', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('58-6991707', 'Auer, Bechtelar and Deckow', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('06-2433633', 'Hegmann LLC', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('40-1485990', 'Weissnat-Kunde', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('47-4481722', 'Schowalter, Hudson and Gutmann', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('98-7699081', 'Dach-Blanda', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('12-7742161', 'Trantow-Ernser', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('45-4868966', 'Wuckert-Bayer', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('23-6133055', 'Keeling LLC', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('25-3413976', 'Frami-Davis', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('54-9747887', 'Becker, Runolfsson and Dicki', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('09-7967258', 'Heathcote-Mann', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('68-2302377', 'Bergstrom Group', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('32-3255436', 'Murazik-Hilll', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('41-8095355', 'Homenick, Greenholt and Lockman', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('87-0284501', 'Prohaska, Pacocha and Kiehn', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('62-6641061', 'Renner, Brekke and Breitenberg', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('75-8344793', 'Bergnaum, Abbott and Kuhlman', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('25-3918248', 'Nikolaus and Sons', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('15-6793173', 'Pouros-Herzog', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('77-4954215', 'Metz-Kling', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('12-4926062', 'Padberg-Feil', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('56-3999391', 'Runte, Bradtke and Pouros', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('52-2232012', 'Ortiz Inc', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('67-2824462', 'Schmidt Inc', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('47-6483141', 'Schamberger Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('41-3014457', 'Flatley, Cronin and Kozey', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('91-7809142', 'Carroll-Quigley', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('44-0826957', 'Ziemann-Hahn', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('95-8093415', 'Gislason-MacGyver', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('85-0456581', 'Kovacek and Sons', 'Malaysia');
INSERT INTO merchands (code, name, country) VALUES ('27-8263682', 'Fisher Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('37-2421122', 'Torp-Vandervort', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('03-8755428', 'Flatley-Glover', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('83-4620221', 'Pfannerstill and Sons', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('21-4163959', 'Moore-Leuschke', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('15-6018834', 'Conroy-Hettinger', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('92-4148450', 'Eichmann-Goyette', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('82-7538516', 'Bailey LLC', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('15-8860807', 'Pacocha Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('34-4260247', 'Macejkovic LLC', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('02-0054042', 'Grimes-Gulgowski', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('09-1852603', 'Weimann, Schmitt and Fritsch', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('41-8602659', 'Pacocha-Heller', 'Malaysia');
INSERT INTO merchands (code, name, country) VALUES ('61-9070478', 'Mante and Sons', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('04-5419281', 'Wunsch Inc', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('85-8486912', 'Ortiz Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('77-0467708', 'Mosciski Inc', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('30-0056285', 'Farrell, Ondricka and Quigley', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('16-7875384', 'King, Maggio and Waelchi', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('73-8701129', 'Hayes Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('39-5071739', 'Pagac-Fisher', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('60-6516449', 'Wehner and Sons', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('69-5657080', 'Cole Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('64-1189878', 'Schmitt LLC', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('75-6812313', 'McDermott Inc', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('14-4753696', 'Grant, Emmerich and Rowe', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('04-6548048', 'Keebler Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('44-3387143', 'Flatley Inc', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('89-5966991', 'Frami Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('02-2374241', 'Senger, Romaguera and Heidenreich', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('36-6873095', 'Dicki Inc', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('21-5762789', 'Kovacek Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('96-2020132', 'Braun Inc', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('01-3915961', 'Rau, Strosin and Prosacco', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('64-0386068', 'Howell Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('52-3737976', 'Sanford Inc', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('91-5482631', 'Von, Luettgen and Connelly', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('33-4958828', 'Grimes, Osinski and Schmeler', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('29-1524228', 'Reilly-Tromp', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('61-4614952', 'Medhurst, Rowe and Farrell', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('15-5105297', 'D''Amore, Mraz and Bernhard', 'Thailand');
INSERT INTO merchands (code, name, country) VALUES ('77-1876172', 'Koepp, Christiansen and Kessler', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('74-3500208', 'McLaughlin, Hessel and Kuhn', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('65-2680894', 'Jacobs Inc', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('89-4898659', 'Goodwin and Sons', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('91-1979093', 'Hane Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('62-1713822', 'Towne Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('29-9200477', 'Lockman Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('45-6932068', 'Murazik Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('41-7239617', 'Grimes Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('73-1986168', 'Bayer Group', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('35-7899633', 'Terry, Quitzon and Heathcote', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('28-6999346', 'Herman-Parker', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('47-0770742', 'Bartoletti and Sons', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('68-8905416', 'Smith and Sons', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('16-3662529', 'Harber-Jones', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('61-8229071', 'Gerhold, Predovic and Oberbrunner', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('11-4887732', 'Von-O''Reilly', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('92-6734474', 'Auer and Sons', 'Indonesia');
INSERT INTO merchands (code, name, country) VALUES ('60-3937042', 'Kovacek, Stoltenberg and Buckridge', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('33-5792607', 'Parisian and Sons', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('63-7845438', 'Heidenreich, McCullough and Goldner', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('32-1723550', 'Adams-Paucek', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('67-8345703', 'Thompson-Nicolas', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('87-3997294', 'Oberbrunner, Koss and Batz', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('15-3840815', 'Williamson, Larkin and Gutmann', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('60-7317655', 'Williamson, Ferry and Cartwright', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('91-3372515', 'Hilpert-Durgan', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('75-9291957', 'Kozey, Wolf and Harris', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('37-9725718', 'Jast Inc', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('49-7202229', 'Feeney-Schaden', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('16-0229337', 'Bruen LLC', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('97-5778943', 'Huels-D''Amore', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('76-9483936', 'Stiedemann, Tromp and Kerluke', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('40-1245696', 'Lebsack LLC', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('03-0025331', 'Senger-Price', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('93-4908000', 'Breitenberg-Johnson', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('28-6214076', 'Weimann LLC', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('07-4633473', 'Hettinger Group', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('22-9806329', 'Bode LLC', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('24-8485933', 'Jacobson-Lueilwitz', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('90-9648338', 'Armstrong, McCullough and Brekke', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('15-5839018', 'Pollich-Denesik', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('97-5331326', 'Lakin Inc', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('99-7177282', 'Cartwright-Wisozk', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('56-4633678', 'Klocko-Goldner', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('02-3071047', 'Streich, O''Conner and Hand', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('51-3421295', 'Powlowski and Sons', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('16-0102196', 'Bechtelar Group', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('15-7685470', 'Grant LLC', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('66-5549206', 'Brekke, Hammes and Mosciski', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('99-1205984', 'Bogan-Barrows', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('82-3230881', 'Moen and Sons', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('86-7940513', 'Lind-Baumbach', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('46-6136007', 'Lesch-Breitenberg', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('93-4987626', 'Considine, Bednar and Grimes', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('29-1908968', 'Schamberger-Stiedemann', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('41-5559223', 'Collier and Sons', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('15-1019132', 'Nienow and Sons', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('00-8348985', 'Mitchell, Willms and Langosh', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('58-8222766', 'Pagac-Marvin', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('50-2612959', 'Schaefer-O''Hara', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('41-6715590', 'Hintz LLC', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('60-8290423', 'Torphy, Funk and Kiehn', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('30-5416560', 'Flatley-Senger', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('95-4160682', 'Kuhic-Becker', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('77-5472983', 'Feest Inc', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('11-3492036', 'Prohaska Inc', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('26-0087539', 'Wolff-Bailey', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('30-2645712', 'Ernser Group', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('71-2629649', 'Wisozk, Tillman and Watsica', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('78-3151659', 'Hintz-Glover', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('57-6774544', 'Olson, Corwin and Emard', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('96-1035157', 'Lindgren, Cole and McLaughlin', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('10-3611942', 'Kautzer-Greenfelder', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('86-9289097', 'Paucek-Wisozk', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('72-7135415', 'Toy Inc', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('47-1797926', 'Morissette-Gutmann', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('14-3452524', 'Wiegand and Sons', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('44-6155344', 'Bernhard and Sons', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('69-6023872', 'Zboncak, Gulgowski and Stracke', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('93-0914476', 'Gutmann-Willms', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('34-2362688', 'Corkery LLC', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('87-5899014', 'Nicolas, Olson and Krajcik', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('33-0655551', 'Barton-Wyman', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('45-2211045', 'Marks-Keeling', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('74-3189383', 'Lemke, Pfeffer and Botsford', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('92-7083470', 'Funk-Weimann', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('79-3680420', 'Howell, Rau and Emmerich', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('61-1157969', 'Mayert-Walker', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('89-8139335', 'Emard-Murazik', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('43-1920878', 'Cremin-Terry', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('93-3283555', 'Runte LLC', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('91-3946329', 'Feeney, Jacobs and Kling', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('54-9383336', 'Kihn, Rolfson and Satterfield', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('74-0549059', 'Swift-Spencer', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('51-6368305', 'Ferry, Gutkowski and Rowe', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('36-1853347', 'Hilll and Sons', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('02-3349519', 'Greenholt, Goodwin and Hayes', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('85-6789083', 'Leffler, Carroll and Gerlach', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('26-4326062', 'Will-Kreiger', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('18-0392768', 'Ward-McDermott', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('69-5903465', 'Kessler-Bernhard', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('47-4200344', 'O''Keefe Group', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('16-2152044', 'Johnson Group', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('85-3850662', 'Barrows-Murray', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('96-2661341', 'Bogan-Lang', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('80-6263963', 'Ryan, Dicki and Runte', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('81-9259098', 'Sauer-Shields', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('35-5187046', 'Rutherford-Ward', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('95-9681180', 'Mraz-Kulas', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('99-4720217', 'Ferry-Smith', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('11-4988012', 'Hagenes and Sons', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('59-5842640', 'Raynor, Swift and Legros', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('11-4453651', 'Kunze Group', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('43-8886336', 'Moore Inc', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('84-6185276', 'Crona, Deckow and Dickens', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('84-7405632', 'Gutmann and Sons', 'Singapore');
INSERT INTO merchands (code, name, country) VALUES ('88-1367074', 'Thiel, Bode and Keebler', 'Singapore');